#!/usr/bin/env python3
"""
Fetch all tinycrops GitHub Pages sites, summarize each with gpt-5.4-mini,
and write frontend/index.html.

Requires: OPENAI_API_KEY, GITHUB_TOKEN env vars.
"""
import os
import json
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

import httpx

OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
ORG = "tinycrops"
MODEL = "gpt-4.1-mini"
OUT_PATH = Path(__file__).parent.parent / "frontend" / "index.html"

SKIP_REPOS = {"tinycrops-index"}  # don't index ourselves

GH_HEADERS = {"Authorization": f"Bearer {GITHUB_TOKEN}", "Accept": "application/vnd.github+json"}


def gh_list_repos():
    repos = []
    page = 1
    while True:
        r = httpx.get(
            f"https://api.github.com/users/{ORG}/repos",
            params={"type": "public", "per_page": 100, "page": page},
            headers=GH_HEADERS,
            timeout=20,
        )
        r.raise_for_status()
        batch = r.json()
        if not batch:
            break
        repos.extend(batch)
        page += 1
    return repos


def get_pages_url(repo_name):
    r = httpx.get(
        f"https://api.github.com/repos/{ORG}/{repo_name}/pages",
        headers=GH_HEADERS,
        timeout=10,
    )
    if r.status_code != 200:
        return None
    return r.json().get("html_url")


def fetch_page_text(url, max_chars=12000):
    try:
        r = httpx.get(url, follow_redirects=True, timeout=15)
        if r.status_code != 200:
            return None
        # strip HTML tags naively
        text = re.sub(r"<[^>]+>", " ", r.text)
        text = re.sub(r"\s+", " ", text).strip()
        return text[:max_chars]
    except Exception as e:
        print(f"  fetch failed: {e}", file=sys.stderr)
        return None


def summarize(title, url, text):
    prompt = (
        f"You are summarizing a published research/project page for an index site.\n"
        f"Page title: {title}\n"
        f"URL: {url}\n\n"
        f"Page content (truncated):\n{text}\n\n"
        f"Write a 2-3 sentence summary that captures: what was measured or built, "
        f"the key finding or result, and who it matters to. "
        f"Be specific and concrete. Plain prose, no bullets, no markdown."
    )
    r = httpx.post(
        "https://api.openai.com/v1/chat/completions",
        headers={"Authorization": f"Bearer {OPENAI_API_KEY}", "Content-Type": "application/json"},
        json={
            "model": MODEL,
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": 200,
            "temperature": 0.3,
        },
        timeout=30,
    )
    r.raise_for_status()
    return r.json()["choices"][0]["message"]["content"].strip()


def build_html(sites):
    date_str = datetime.utcnow().strftime("%B %Y")
    cards = ""
    for s in sites:
        cards += f"""
  <div class="card">
    <a class="title" href="{s['url']}" target="_blank" rel="noopener">{s['name']}</a>
    <p class="summary">{s['summary']}</p>
    <a class="link" href="{s['url']}" target="_blank" rel="noopener">{s['url']}</a>
  </div>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>tinycrops — published work</title>
<style>
  :root{{
    --bg:#0e0f13; --panel:#14161c; --line:#2a2d34;
    --ink:#e8e4d8; --sub:#9a958a; --amber:#ffb000; --teal:#27c4c4; --grey:#6a6f78;
  }}
  *{{box-sizing:border-box}}
  body{{margin:0;background:var(--bg);color:var(--ink);font-family:Georgia,'DejaVu Serif',serif;line-height:1.55}}
  .wrap{{max-width:860px;margin:0 auto;padding:52px 28px 90px}}
  h1{{font-size:2rem;letter-spacing:.06em;margin:0 0 4px;color:var(--amber)}}
  .kicker{{color:var(--sub);font-style:italic;margin-bottom:2px;font-size:.95rem}}
  .date{{color:var(--grey);font-size:.8rem;margin-bottom:56px}}
  .card{{background:var(--panel);border:1px solid var(--line);border-radius:6px;
         padding:22px 24px 18px;margin-bottom:18px}}
  .card .title{{font-size:1.12rem;color:var(--amber);text-decoration:none;font-style:italic}}
  .card .title:hover{{color:var(--teal)}}
  .card .summary{{color:var(--ink);margin:10px 0 10px;font-size:.95rem}}
  .card .link{{font-size:.78rem;color:var(--grey);text-decoration:none;font-family:monospace}}
  .card .link:hover{{color:var(--teal)}}
  .foot{{margin-top:60px;border-top:1px solid var(--line);padding-top:14px;
         color:var(--grey);font-size:.78rem;font-style:italic}}
</style>
</head>
<body>
<div class="wrap">
<p class="kicker">tinycrops · a record of things made</p>
<h1>PUBLISHED WORK</h1>
<p class="date">auto-summarized {date_str} · {len(sites)} sites</p>
{cards}
<div class="foot">summaries generated by {MODEL} from live page content · index updates on new publish</div>
</div>
</body>
</html>"""


def main():
    print("Listing repos...", file=sys.stderr)
    repos = gh_list_repos()
    print(f"Found {len(repos)} public repos", file=sys.stderr)

    sites = []
    for repo in repos:
        name = repo["name"]
        if name in SKIP_REPOS:
            continue
        pages_url = get_pages_url(name)
        if not pages_url:
            continue
        print(f"  {name} → {pages_url}", file=sys.stderr)
        text = fetch_page_text(pages_url)
        if not text:
            print(f"    skipped (no content)", file=sys.stderr)
            continue
        try:
            summary = summarize(name, pages_url, text)
        except Exception as e:
            print(f"    summarize failed: {e}", file=sys.stderr)
            summary = "Summary unavailable."
        sites.append({"name": name, "url": pages_url, "summary": summary})
        print(f"    summarized", file=sys.stderr)

    # Sort newest-first by repo name (lexicographic works fine for dated names; others stay stable)
    sites.sort(key=lambda s: s["name"], reverse=True)

    html = build_html(sites)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(html)
    print(f"Wrote {OUT_PATH} ({len(sites)} sites)", file=sys.stderr)


if __name__ == "__main__":
    main()
